name: artemis_app
description: "A Flutter app for exploring scientific publications using the OpenAlex API."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.1
  google_sign_in: ^6.3.0
  flutter_localizations:
    sdk: flutter
  intl: any
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  go_router: ^16.3.0
  riverpod: ^3.0.3

  isar_community: ^3.3.0-dev.3
  isar_community_flutter_libs: ^3.3.0-dev.3

  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  firebase_core: ^4.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  envied: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3  
  isar_community_generator: ^3.3.0-dev.3
  mocktail: ^1.0.0

  freezed: ^3.2.3
  json_serializable: ^6.9.0
  envied_generator: ^1.3.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/discover_new_ideas.svg
    - assets/svg/google_icon_logo.svg
    - assets/svg/login.svg